# Generated by Django 5.1.5 on 2025-03-01 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ReportCard", "0002_subject_subjectmarks"),
    ]

    operations = [
        migrations.CreateModel(
            name="rank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_of_report_card_generation", models.DateField(auto_created=True)),
                ("student_rank", models.IntegerField()),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="studentreportcard",
                        to="ReportCard.student",
                    ),
                ),
            ],
        ),
    ]
