# Generated by Django 5.1.5 on 2025-03-01 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ReportCard", "0003_rank"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="rank",
            new_name="students_rank",
        ),
        migrations.AlterUniqueTogether(
            name="students_rank",
            unique_together={("student_rank", "date_of_report_card_generation")},
        ),
    ]
