# Generated by Django 5.1.5 on 2025-03-01 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ReportCard", "0004_rename_rank_students_rank_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="students_rank",
            name="date_of_report_card_generation",
            field=models.DateField(auto_now_add=True),
        ),
    ]
