# Generated by Django 5.1.5 on 2025-03-01 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ReportCard", "0005_alter_students_rank_date_of_report_card_generation"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="students_rank",
            new_name="ReportCard",
        ),
    ]
